"""
AI-driven Zillow Preferred metric + threshold researcher.

Called at the start of each monthly run to web-search the *current* Zillow
Preferred program KPIs and their target thresholds, then writes them to
config/thresholds.json.

The set of metrics is itself researched (not hard-coded) — Zillow updates the
program periodically, so the previous month's metric list is treated as a hint,
not a contract. Whatever Zillow currently publishes wins.
"""

import json
import logging
import shutil
from datetime import date

import anthropic

from config.settings import (
    ANTHROPIC_API_KEY,
    RESEARCH_MAX_TOKENS,
    RESEARCH_MODEL,
    THRESHOLDS_FILE,
)

log = logging.getLogger(__name__)

RESEARCH_PROMPT = """
You are a real estate industry researcher. Your task is to find the CURRENT
Zillow Preferred Agent program performance KPIs for {year}, including which
metrics Zillow is currently using to evaluate agents — Zillow changes this
program periodically, so do not assume the same KPIs as previous years.

For each KPI Zillow currently tracks, return:
- key:           short snake_case identifier (e.g. "speed_to_action")
- label:         human-readable name (e.g. "Speed to Action")
- unit:          one of "percent" | "score" | "count" | "seconds"
- target:        numeric target threshold (preferred = green)
- yellow_floor:  numeric value below which agent is "at risk" (~85–90% of target)
- direction:     "higher_is_better" or "lower_is_better"
- weight:        relative importance 0.0–1.0 (1.0 = most important)
- gauge_size:    "hero" for the single most important metric, "secondary" for others
- description:   one-sentence description of what the metric measures

Return ONLY a JSON object in this exact shape:
{{
  "source_notes": "Where you found this — URLs, dates, etc.",
  "metrics": {{
    "<metric_key>": {{
      "label": "<string>",
      "unit": "<percent|score|count|seconds>",
      "target": <number>,
      "yellow_floor": <number>,
      "direction": "<higher_is_better|lower_is_better>",
      "weight": <number>,
      "gauge_size": "<hero|secondary>",
      "description": "<string>"
    }},
    ...
  }}
}}

Rules:
- Include EVERY current program KPI you can identify with confidence.
- Mark exactly ONE metric as gauge_size "hero" (the most heavily weighted).
- If a value is unknown, use null and note it in source_notes. Do not guess.
- Return only the JSON, no preamble or commentary.
""".strip()


def research_thresholds(year: str | None = None) -> dict:
    """
    Use Claude with web search to find current Zillow Preferred KPIs + thresholds.

    Returns the parsed research results dict.
    Raises on API errors or unparseable responses.
    """
    if not ANTHROPIC_API_KEY:
        raise OSError(
            "ANTHROPIC_API_KEY is not set. Export it before running:\n"
            "  export ANTHROPIC_API_KEY=your_key_here"
        )

    target_year = year or str(date.today().year)
    prompt = RESEARCH_PROMPT.format(year=target_year)

    log.info("Researching Zillow Preferred %s KPIs via Claude API…", target_year)

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    response = client.messages.create(
        model=RESEARCH_MODEL,
        max_tokens=RESEARCH_MAX_TOKENS,
        tools=[{"type": "web_search_20250305", "name": "web_search"}],
        messages=[{"role": "user", "content": prompt}],
    )

    result_text = None
    for block in response.content:
        if hasattr(block, "text"):
            result_text = block.text.strip()
            break

    if not result_text:
        raise ValueError("Claude returned no text content in research response.")

    if result_text.startswith("```"):
        lines = result_text.splitlines()
        result_text = "\n".join(line for line in lines if not line.startswith("```")).strip()

    try:
        parsed = json.loads(result_text)
    except json.JSONDecodeError as e:
        log.error("Could not parse Claude response as JSON:\n%s", result_text)
        raise ValueError(f"Claude research returned non-JSON: {e}") from e

    log.info("Research complete. Source: %s", parsed.get("source_notes", "N/A"))
    return parsed


def update_thresholds_file(research_results: dict, year: str | None = None) -> None:
    """
    Overwrite the metrics block with researched values.

    Backs up the previous file to thresholds.json.bak before overwriting so a
    bad research result can be reverted by the admin.
    """
    if THRESHOLDS_FILE.exists():
        shutil.copy(THRESHOLDS_FILE, THRESHOLDS_FILE.with_suffix(".json.bak"))

    target_year = year or str(date.today().year)
    researched_metrics = research_results.get("metrics", {})

    if not researched_metrics:
        raise ValueError("Research returned no metrics. Refusing to overwrite thresholds.json.")

    new_doc = {
        "_comment": (
            "Auto-generated by src/threshold_researcher.py. "
            "Both the metric set and thresholds are researched each run."
        ),
        "last_updated": date.today().isoformat(),
        "source": research_results.get("source_notes", "AI research"),
        "program_year": target_year,
        "metrics": researched_metrics,
    }

    with open(THRESHOLDS_FILE, "w") as f:
        json.dump(new_doc, f, indent=2)

    log.info("thresholds.json updated at %s", THRESHOLDS_FILE)


def run_research(year: str | None = None) -> None:
    """Top-level function called by main.py --mode research."""
    results = research_thresholds(year)
    update_thresholds_file(results, year)
    print("\nThresholds updated successfully.")
    print(f"Source: {results.get('source_notes', 'N/A')}")
    print(f"File:   {THRESHOLDS_FILE}\n")

    metrics = results.get("metrics", {})
    print(f"{'Metric':<24} {'Target':>10} {'Yellow':>10} {'Dir':>6} {'Unit':>8}")
    print("-" * 64)
    for key, m in metrics.items():
        target = m.get("target", "N/A")
        floor = m.get("yellow_floor", "N/A")
        unit = m.get("unit", "")
        direction = "↑" if m.get("direction") == "higher_is_better" else "↓"
        print(f"{key:<24} {str(target):>10} {str(floor):>10} {direction:>6} {unit:>8}")
    print()


if __name__ == "__main__":
    import sys

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    year_arg = sys.argv[1] if len(sys.argv) > 1 else None
    run_research(year_arg)
